-- =====================================================================
-- Oracle -> Zoho Creator sync: schema
-- Run as schema owner (the same user that owns SK1MF / PS33MF / GRBRF).
-- =====================================================================

-- Persistent change-event queue. Replaces DBMS_ALERT (which coalesces).
CREATE TABLE SYNC_EVENTS (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table VARCHAR2(10) NOT NULL,        -- 'SK1MF' | 'PS33MF' | 'GRBRF'
    op           VARCHAR2(1)  NOT NULL,        -- 'I' | 'U' | 'D'
    k_cp         NUMBER(3),
    k_yr         NUMBER(4),
    k_code       VARCHAR2(20),
    k_bn         NUMBER(3),
    enqueued_at  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    status       VARCHAR2(10) DEFAULT 'NEW' NOT NULL,  -- NEW | INFLIGHT | DONE | DEAD
    attempts     NUMBER       DEFAULT 0 NOT NULL,
    last_source_hash VARCHAR2(64),
    last_error   VARCHAR2(4000),
    next_attempt_at TIMESTAMP,
    picked_at    TIMESTAMP,
    finished_at  TIMESTAMP,
    CONSTRAINT chk_sync_op  CHECK (op IN ('I','U','D')),
    CONSTRAINT chk_sync_st  CHECK (status IN ('NEW','INFLIGHT','DONE','DEAD')),
    CONSTRAINT chk_sync_src CHECK (source_table IN ('SK1MF','PS33MF','GRBRF'))
);
CREATE INDEX ix_sync_events_ready ON SYNC_EVENTS(status, next_attempt_at, id);

-- Oracle composite key -> Zoho record id mapping. Required for U / D.
-- k_code is NULL for GRBRF rows; k_bn is NULL for ITEMS rows.
-- Oracle PKs enforce NOT NULL, so we use a surrogate PK + function-based unique index.
CREATE TABLE ZOHO_MAP (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table   VARCHAR2(10) NOT NULL,
    k_cp           NUMBER(3),
    k_yr           NUMBER(4),
    k_code         VARCHAR2(20),
    k_bn           NUMBER(3),
    zoho_record_id VARCHAR2(40) NOT NULL,
    last_synced_at TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX uq_zoho_map ON ZOHO_MAP(
    source_table, NVL(k_cp, -1), NVL(k_yr, -1), NVL(k_code, '~'), NVL(k_bn, -1)
);

-- Backfill resume cursor.
CREATE TABLE BACKFILL_CHECKPOINT (
    source_table VARCHAR2(10) PRIMARY KEY,
    last_cp      NUMBER(3),
    last_yr      NUMBER(4),
    last_code    VARCHAR2(20),
    last_bn      NUMBER(3),
    rows_done    NUMBER       DEFAULT 0  NOT NULL,
    started_at   TIMESTAMP    DEFAULT SYSTIMESTAMP,
    finished_at  TIMESTAMP
);

-- Seed checkpoints (idempotent).
MERGE INTO BACKFILL_CHECKPOINT t
USING (SELECT 'SK1MF' AS s FROM dual UNION ALL
       SELECT 'GRBRF'        FROM dual) src
ON (t.source_table = src.s)
WHEN NOT MATCHED THEN INSERT (source_table) VALUES (src.s);

COMMIT;
